; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define appver = "1.4"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{62EF37D6-329D-4565-8D80-999CBA48E238}
AppName=HourSync
AppVersion=v{#appver}
AppVerName=HourSync v{#appver}
AppPublisher=Neil Patrao
AppPublisherURL=https://hoursync.net
AppSupportURL=https://hoursync.net/support
AppUpdatesURL=https://hoursync.net
DefaultDirName={userdocs}\HourSync
UninstallDisplayIcon={app}\HourSync.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=D:\Code\HourSync\LICENSE.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=D:\Code\HourSync\Installers\{#appver}
OutputBaseFilename=HourSync
SetupIconFile=D:\Code\HourSync\logo.ico
SolidCompression=yes
WizardStyle=modern

WizardImageFile=logo-large.bmp
WizardSmallImageFile=logo.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Root files in publish (no subfolders)
Source: "D:\Code\HourSync\bin\publish\*"; DestDir: "{app}"; Flags: ignoreversion

; Assets folder
Source: "D:\Code\HourSync\bin\publish\Assets\*"; DestDir: "{app}\Assets"; Flags: ignoreversion recursesubdirs createallsubdirs

; en-us localization folder
Source: "D:\Code\HourSync\bin\publish\en-us\*"; DestDir: "{app}\en-us"; Flags: ignoreversion recursesubdirs createallsubdirs

; Microsoft.UI.Xaml folder
Source: "D:\Code\HourSync\bin\publish\Microsoft.UI.Xaml\*"; DestDir: "{app}\Microsoft.UI.Xaml"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\HourSync"; Filename: "{app}\HourSync.exe"
Name: "{autodesktop}\HourSync"; Filename: "{app}\HourSync.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\HourSync.exe"; Description: "{cm:LaunchProgram,HourSync}"; Flags: nowait postinstall skipifsilent

